### PR TITLE
README FILE BADGES IMPROVE 

### LINKED ISSUE #19: README FILE BADGES IMPROVE
Hi @harshsbais 
There are no badges or shields in the readme file , Kindly assign me if you would like to see more badges in it 
I would be glad to work on it pls bro 

readme1

### PR DESCRIPTION
**Pull request by akrish4**
Hi @harshsbais 
Fixed : #19 

Kindly do add the same labels thats is added in issue to pr too 

Thank you 

@harshsbais

### CODE REVIEW

**Comment by adityaraute** [comment]
@akrish4 you should squash similar commits. And commit after making all changes together. This looks like you are spamming commits for whatever reason

**Comment by akrish4** [comment]
> @akrish4 you should squash similar commits. And commit after making all changes together. This looks like you are spamming commits for whatever reason

Hi @dumbcoder7 
This is a markdown file so i don't have to clone it locally and can edit it in github itself so when editing it , it just increases the commits accordingly and it has fine there is no issues if commit is increased also it just happens while editing markdown , while continuous editing , the commit increases  , hope u understand

**Comment by akrish4** [comment]
and @dumbcoder7  , if it matters then maintainer has an option to squash and merge so you don't have to worry abt it , maintainers have option to squash and merge it as 1 commit

**Comment by adityaraute** [comment]
Sure but you could also try the `Preview` tab for README files, in case you were unaware. So you do not have to commit all changes separately.

**Comment by akrish4** [comment]
oh yeah I just came to know abt that  `Preview` tab is available for README also I thought its available only for  *issues* and *pr* 
And it doesn't matter at all to the repository , the commit just increases in the flow as in each edit there may be new bug or improvements and hence the commit increases , but now onwards i will use preview tab for readme 
 thank you

**Pull request merged**
