### PR TITLE
Added MacOS Distribution

### PR DESCRIPTION
**Pull request by infiniteoverflow**
Fixes issue #10

### CODE REVIEW

**Comment by infiniteoverflow** [comment]
@harshsbais kindly have a look. I have added the dist files inside the Amazon_price_tracker folder

**Comment by harshsbais** [comment]
remove these build files from the pr.

**Comment by infiniteoverflow** [comment]
@harshsbais I have fixed it kindly have a look.

**Comment by harshsbais** [comment]
where is the dmg file placed

**Comment by infiniteoverflow** [comment]
@harshsbais Sorry , i had added the .app file. Now i have updated it to contain the .dmg file. Kindly have a check. Thank you.

**Comment by infiniteoverflow** [comment]
@harshsbais Can anything be done about this PR ?

**Comment by harshsbais** [comment]
I checked the dmg it is not opening

**Pull request closed without merging**
